[project]
name = "brainy"
queries = "db"
container_runtime = "docker"

[local.dev]
port = 6969
image = "ghcr.io/helixdb/helixdb"
tag = "v0.0.6"
storage = "disk"

[local.slot2]
port = 6970
image = "ghcr.io/helixdb/helixdb"
tag = "v0.0.6"
storage = "disk"

[enterprise]
